language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist
  user: mainro
  password:
    secure: QKj0vyIzPUEdIhf+19nalRBf0LXC7flWkUvj8yWU5qCg94MxWHA+gXob6DeCLf8D4fik9qzRnfzcras/DMZgqgpEjhw99aSSA9pSVLk7cQ6SwHlLLQlLhh4cP4LolRHfFfwVKHP+1BKVJ7EqqYH/+ycDS9Jq8hYwq4UTFEk4WI+AGrGM8d04syHqmLXVBFo5mAjwQzSz65JF8NhKyyfoizmlm6Dwy3ysYNOKqfSyHKjoHMEsG1fnKJCOmCLSuw6zvNkBJ3w9Lg+OOr0LMOoKaYUf25FgPARKFn4UpeLkF1A063nqPA5xPoJFbRViKcczjel0VF2BFR6XPFbDNlIysTjyrWX+DQcsBVDQSIsOsRRuL8AS3E02UOeapRTHQ7eevcI6/Aa1BM3pQYEtrrqt0aECOOrrNpUUb8M6DoTwQvhb+X2xgZcn7FTeURF0ZST06Vu8yNpgf9mOYj5etdQd+lk2r9SNxec2MwgdgK568eFdbc1CFse1RM9p/KeVJ3mqpVr/1irOqWZ0VRqRsvp7KS5DZvU0HpPWmwF96qKiJuW5QCNqKH8x87oCPLzf7H3Y3jVHH7FRzjWn7c5BXKI/rsEZQK/sHZfLaFDv0EQRUj53JclP3ehZ/zMCnMFRpOos0wftadNDXrfe5+chfc3Wlc6Iaxu8GGcq4VyRb+H5NCM=
  on:
    tags: true
